<a href="https://colab.research.google.com/github/luoChengwen/Time-Series-Prediction/blob/master/basic_preprocessing_feature_preperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# !pip install tf-nightly-2.0-preview
# !pip install tensorflow==2.0.0-beta0



In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.0.0-beta0


In [2]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
   print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [3]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=2)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
2 3 4 5 6 
4 5 6 7 8 
6 7 8 9 
8 9 


In [4]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=2, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
2 3 4 5 6 
4 5 6 7 8 


In [5]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())


[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [6]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())


[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [7]:
test = tf.data.Dataset.range(10)
test = test.window(5,shift=1, drop_remainder = True)
test = test.flat_map(lambda window: window.batch(5))
test = test.map(lambda window: (window[:-1], window[-1:]))
for i,j in test:
    print(i.numpy(),j.numpy())
test = test.shuffle(buffer_size=5)
print('--------------')
for i,j in test:
    print(i.numpy(),j.numpy())


[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]
--------------
[4 5 6 7] [8]
[5 6 7 8] [9]
[0 1 2 3] [4]
[3 4 5 6] [7]
[2 3 4 5] [6]
[1 2 3 4] [5]


In [8]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda x: x.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())


[3 4 5 6] [7]
[1 2 3 4] [5]
[0 1 2 3] [4]
[5 6 7 8] [9]
[4 5 6 7] [8]
[2 3 4 5] [6]


In [9]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
    print("x = ", x.numpy())
    print("y = ", y.numpy())

print('--------------')
test3 = test.batch(2) 
for i,j in test3:
    print(i.numpy(),type(i.numpy()),np.shape(i.numpy()))
    print(j.numpy())
print('--------------')
test2 = test.batch(2).prefetch(1)
for i,j in test2:
    print(i.numpy(),type(i.numpy()),np.shape(i.numpy()))
    print(j.numpy())

x =  [[4 5 6 7]
 [5 6 7 8]]
y =  [[8]
 [9]]
x =  [[1 2 3 4]
 [2 3 4 5]]
y =  [[5]
 [6]]
x =  [[3 4 5 6]
 [0 1 2 3]]
y =  [[7]
 [4]]
--------------
[[4 5 6 7]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)
[[8]
 [9]]
[[0 1 2 3]
 [3 4 5 6]] <class 'numpy.ndarray'> (2, 4)
[[4]
 [7]]
[[2 3 4 5]
 [1 2 3 4]] <class 'numpy.ndarray'> (2, 4)
[[6]
 [5]]
--------------
[[4 5 6 7]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)
[[8]
 [9]]
[[0 1 2 3]
 [3 4 5 6]] <class 'numpy.ndarray'> (2, 4)
[[4]
 [7]]
[[2 3 4 5]
 [1 2 3 4]] <class 'numpy.ndarray'> (2, 4)
[[6]
 [5]]
